### ISSUE TITLE
SVG icons

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/Vivify#102]
- for directory list to replace current 📁 and 📄
- for up/back button after #82 is merged

**Comment by jannis-baum** [comment]
some MIT-licensed options: 

- GitHub icons: https://github.com/primer/octicons
- Feather: https://feathericons.com

**Comment by tuurep** [comment]
Nice, lets view:

## Octicon

![file-directory](https://github.com/user-attachments/assets/5d092bc1-7799-435b-bb9d-205e01c3529f)
![file-directory-fill](https://github.com/user-attachments/assets/a4210ad7-5552-40f0-b737-72812f709740)
![file-directory-open-fill](https://github.com/user-attachments/assets/5cd07eb8-a946-4d47-86cf-1ea4ea437be9)
![file](https://github.com/user-attachments/assets/c4cf2560-a629-48c1-9a0c-6637da8a2c5f)

## Feather

![folder](https://github.com/user-attachments/assets/66f3004b-8359-4025-b64c-c5e31e446bda)
![file](https://github.com/user-attachments/assets/f141a7c3-0e8b-4067-899b-09c3a51fadb5)
![file-text](https://github.com/user-attachments/assets/bfde4f6a-c193-43d6-bf62-a3f53ead135d)

---

Both are nice and clean. I think I vote for octigon, particularly black folders and white files.

![file-directory-fill](https://github.com/user-attachments/assets/3fb4120f-9e3f-48df-b396-b3e24c4ccaa3)
![file](https://github.com/user-attachments/assets/da6fe575-f4ee-4ad2-a350-d139aeda7787)

What do you think?

**Comment by tuurep** [comment]
Oh I see, Github uses those:

![image](https://github.com/user-attachments/assets/c7968d7c-802d-431d-8a82-d85ea2476f5b)

But with colors

One option is to mimic this as well

**Comment by jannis-baum** [comment]
Ah nice, thanks for checking that out already! Yes I agree, I also prefer the GitHub icons

**Comment by Tweekism** [comment]
@jannis-baum 

When trying to drag this to myself on the projects board I get this.

![image](https://github.com/user-attachments/assets/ff0e13ad-73a4-4cee-af57-ba3a7b0b84f0)

**Comment by jannis-baum** [comment]
> When trying to drag this to myself on the projects board I get this.

I invited you to be a collaborator, after you accept that it should work :)

**Comment by Tweekism** [comment]
riiiiight, umm, and where / how might one do that, lmao.

I'll find it...

**Comment by jannis-baum** [comment]
Probably in your emails ^^

**Comment by Tweekism** [comment]
My emails are a disaster, never go there.

You must have resent, it showed up in my GitHub notifications, works now.

Thanks.

**Comment by Tweekism** [comment]
@tuurep I'm also going to look into the Windows port. So if you'd like to take this one you are welcome to.

**Comment by tuurep** [comment]
Hey, yeah I could do this one gladly and incorporate my critisism of #82  if that's ok

**Comment by Tweekism** [comment]
That'd be awesome. I agree with the critique. I hated it immedately, but hit target was too small without and I wanted to get something merged, figured I'd fix it later lol.

**Comment by tuurep** [comment]
Ok, good to know as well!

**Comment by tuurep** [comment]
I'll start this right now

@jannis-baum I imagine we have to download and place the icons somewhere in the repo, where should I put them?

Maybe something like

```
static/icons/file.svg
static/icons/directory.svg
```

?

**Comment by tuurep** [comment]
Ah I forgot how svg works lol

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M2 4.75C2 3.784 2.784 3 3.75 3h4.971c.58 0 1.12.286 1.447.765l1.404 2.063c.046.069.124.11.207.11h8.471c.966 0 1.75.783 1.75 1.75V19.25A1.75 1.75 0 0 1 20.25 21H3.75A1.75 1.75 0 0 1 2 19.25Z"></path></svg>
```

Preferable to use them in this format?

**Comment by tuurep** [comment]
Ah, yet another way. I can do that then, sure.

**Comment by jannis-baum** [comment]
I think whatever way you can find that requires the least amount of copying is good ^^ so that we can easily update it

**Comment by tuurep** [comment]
Minimum effort sneak peek:

![image](https://github.com/user-attachments/assets/605355ef-8e29-4ae1-925a-22b0911e1278)

Style wise I just have to tweak the alignment and spacing

It appeared like I could not use the `@primer/octicons` as a module, leading me to this issue: https://github.com/nodejs/single-executable/issues/87

Does that look accurate?

But inline tags are just fine for our use I suppose.

The "icon as part of link" part is absolutely trivial, I just need to slap the `<svg>` inside the `<a>` and I find it ideal: if you hover on the icon, the text gets underlined.

Continuing tomorrow :)

**Comment by tuurep** [comment]
> for up/back button after https://github.com/jannis-baum/Vivify/pull/82 is merged

Hey I almost missed this, do we still need a new icon for this?

I guess so, since it's the unicode symbol currently.

**Comment by jannis-baum** [comment]
Nice, looks cool!

> It appeared like I could not use the @primer/octicons as a module, leading me to this issue: nodejs/single-executable#87
>
> Does that look accurate?

Hm, no, that shouldn't be an issue since we do bundle everything into a single file with webpack before injection. Otherwise we couldn't use any external plugins

**Comment by tuurep** [comment]
Thanks, I'll recheck the module usage

Would be best if one of the octicon icons worked for the back icon, some suggestions:

![triangle-left](https://github.com/user-attachments/assets/6f60f777-facc-4e5e-a457-99a41f8db162)

^ Most similar to the current one?

![reply](https://github.com/user-attachments/assets/fd4bb55d-a02c-4565-af84-30b94cc2596c)

![undo](https://github.com/user-attachments/assets/0ab839e1-0b9f-4dd2-99b9-4098847a1ab0)

![chevron-left](https://github.com/user-attachments/assets/a42c131f-d012-4a01-b092-be3118f812e4)

![arrow-left](https://github.com/user-attachments/assets/773adc65-b013-4c4b-89f5-1cb00e480101)

**Comment by Tweekism** [comment]
I like the solid triangle and I like the bottom 2. The middle 2 options look more like "reply" (like in email) and "undo"

**Comment by jannis-baum** [comment]
I prefer the bottom two; the chevron and the plain left arrow :)

**Comment by Tweekism** [comment]
Out of those two, I think I slightly prefer the chevron

**Comment by tuurep** [comment]
Gotcha, I'll prioritize that one and lets see how it looks
