### ISSUE TITLE
Misc release adjustments

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/Vivify#107]
- [x] move `release.sh` script to `.github` so the root is cleaner
- [x] switch to `.tar.gz` to archive release binaries
- [x] rework release notes
  - use tag description
  - add SHA256 sums

**Comment by jannis-baum** [comment]
Hey @tuurep just as a heads up, I made the adjustments in the list above to how the releases work. I need the SHA256 sums for the Homebrew release, maybe you need them as well. Anyways, including them in the release notes was the main motivation for this.

Additionally I also switched to `.tar.gz` because it seems to be more conventional and I swapped out the automatically generated release notes for a wrapped version of the "commit message"-equivalent of the release tag so that we get nicer and more organized release notes.

**Comment by tuurep** [comment]
Ok! all of that is probably fine

I've been adding md5sums in the AUR package but can use the sha256 as well

**Comment by jannis-baum** [comment]
> I've been adding md5sums in the AUR package but can use the sha256 as well

Alright! If you think having md5 in the release notes would be useful I can also just add those as well :) let me know

How have you been getting the md5sum up until now? Download the file and then compute it locally?

**Comment by tuurep** [comment]
I don't really know much about those and just added the first thing I could google since the PKGBUILD required it :D so having just sha256 is fine

> How have you been getting the md5sum up until now? Download the file and then compute it locally?

Yep exactly, with: https://man.archlinux.org/man/md5sum.1.en

**Comment by tuurep** [comment]
Hey I found another Arch Wiki segment that answers this perfectly:

> The checksum type and values should always be those provided by upstream, such as in release announcements. When multiple types are available, the strongest checksum is to be preferred: `b2` over `sha512`, `sha512` over `sha384`, `sha384` over `sha256`, `sha256` over `sha224`, `sha224` over `sha1`, `sha1` over `md5`, and `md5` over `ck`. This best ensures the integrity of the downloaded files, from upstream announcement to package building.

So we did everything just right :D thanks

**Comment by jannis-baum** [comment]
> Hey I found another Arch Wiki segment that answers this perfectly:
> 
> > The checksum type and values should always be those provided by upstream, such as in release announcements. When multiple types are available, the strongest checksum is to be preferred: `b2` over `sha512`, `sha512` over `sha384`, `sha384` over `sha256`, `sha256` over `sha224`, `sha224` over `sha1`, `sha1` over `md5`, and `md5` over `ck`. This best ensures the integrity of the downloaded files, from upstream announcement to package building.
> 
> So we did everything just right :D thanks

Nice, thanks for looking into it! Sounds good☺️ I really wonder why GitHub doesn't just show checksums by default. [People have been asking for it](https://stackoverflow.com/a/56687640) but it's still not a thing.
