### ISSUE TITLE
Version command

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/Vivify#111]
`-v`/`--version`

**Comment by tuurep** [comment]
(hope it's not obnoxious that I'm leaving stray comments in closed issues)

For AUR package `vivify` the version number looks a little off

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vivify

With `make linux`:

```
$ viv --version
vivify-server 4b5b8a1
```

With `VIV_VERSION="${pkgver}" make linux`

```
$ viv --version
vivify-server 2952cec-dirty
```

(or `VIV_VERSION="foo"` for that matter)

**Comment by tuurep** [comment]
Oh yes, it dawned on me why the versions are what they are,

since it's taking it from parsing some git logs, in the AUR case it parses the AUR repos logs :D

But not sure why setting explicit `VIV_VERSION` gets ignored here

**Comment by jannis-baum** [comment]
> (hope it's not obnoxious that I'm leaving stray comments in closed issues)

Haha no worries at all! I have also been do this to contact you ^^

> Oh yes, it dawned on me why the versions are what they are,
> 
> since it's taking it from parsing some git logs, in the AUR case it parses the AUR repos logs :D

Yes, it looks like this was the fallback `git describe --tags --always --dirty` from the Makefile when there are no tags below the current commit.

> But not sure why setting explicit `VIV_VERSION` gets ignored here

This is indeed weird. Some questions/ideas (may not be relevant to answer all of them):

1. What exactly does `"${pkgver}"` resolve to?
2. Does the `VIV_VERSION="..." make linux` work for you usually?
3. Where is the build script (with the added environment variable setting) at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vivify executed to make it break?
4. Are there versions of `make` that don't support the `?=` assignment syntax?
   https://github.com/jannis-baum/Vivify/blob/4f880106356430a7467c5c1f9dd6a8c900b197b7/Makefile#L18
   If so, could that be it?
5. Could it be that the `make`-step where the bundle is built and the version-string is injected had already run and not been rerun when you tried this? Maybe `VIV_VERSION="..." make -B linux` or cleaning out the build directory will fix it then?

**Comment by tuurep** [comment]
Hey, I just pushed the AUR 0.2.1 version and now using `VIV_VERSION=foo` in the PKGBUILD is working. Not sure if something fixed it as a side effect or what, but yeah this is good.

Also I'm thinking perhaps I should set it something like:

`v0.2.1-aur`

So that if someone opens a bug request and turns out it's an AUR issue, that can point it towards that.

Let me know if there's an objection but otherwise I'll go ahead :)

**Comment by jannis-baum** [comment]
Hey happy to know it resolved itself!

The `-aur` suffix is a great idea! I'll do `-brew` for the Homebrew package as well then

**Comment by jannis-baum** [comment]
> I'll do `-brew` for the Homebrew package as well then

Just FYI, I was just going to do this but then realized it doesn't make any sense since the brew package just downloads the CI-built binaries from the release instead of building again.
