### ISSUE TITLE
Add TOC support for Markdown

### ISSUE THREAD

**Issue by ricardo-jsd-santos** [jannis-baum/Vivify#137]
Thanks for a great project! 

One feature I miss from Vivify is the ability to have a Table Of Contents (TOC) by adding ` [[toc]]` in markdown.

I'm aware that node modules such as [markdown-it-table-of-contents](https://www.npmjs.com/package/markdown-it-table-of-contents?activeTab=dependencies) allow adding a TOC, though I haven't delved into Vivify's code enough to know if it is applicable, but if it is, it could be fairly easy to implement, having done so myself in [another project](https://github.com/twidxuga/vim-instant-markdown). 

Cheers.

**Comment by jannis-baum** [comment]
Hello! Great to hear you like the project! :)

Thanks for already linking a suitable `markdown-it` plugin, this makes this very fast to implement. I just did it and added a table of contents to our testing file for additional Markdown features:

![image](https://github.com/user-attachments/assets/733e14c8-9846-4e2a-bddf-fd7a7298814c)

Is this how you would want/expect it? Or is there some other convention for how to style it?

**Comment by Tweekism** [comment]
Are you speed running feature request implementations now? 😁

**Comment by jannis-baum** [comment]
@ricardo-jsd-santos let me know if the screenshot is how you were imagining this or if we should look into styling it differently! :)

**Comment by ricardo-jsd-santos** [comment]
> Hello! Great to hear you like the project! :)
> 
> Thanks for already linking a suitable `markdown-it` plugin, this makes this very fast to implement. I just did it and added a table of contents to our testing file for additional Markdown features:
> 
> ![image](https://private-user-images.githubusercontent.com/85999315/352812881-733e14c8-9846-4e2a-bddf-fd7a7298814c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzE2NDMsIm5iZiI6MTcyMjE3MTM0MywicGF0aCI6Ii84NTk5OTMxNS8zNTI4MTI4ODEtNzMzZTE0YzgtOTg0Ni00ZTJhLWJkZGYtZmQ3YTcyOTg4MTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDEyNTU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MzhjMThhNzM3OWJmNmZmZWJiNTc2N2U3NDk0MzA1NThiZGQzMmY4ODVhOGYxNDU0MTVkOWM2MzM5OGViYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_TouRKHGVeMZqwGDk9SxHTPD8xtvQMpLnlrRBH_84M)
> 
> Is this how you would want/expect it? Or is there some other convention for how to style it?


Awesome, that is indeed a fast turnaround!

I normally prefer 3 levels of '#' (headings) in TOCs, but I guess 2 or 3 are both good compromises/defaults, that most folks will accept (or it can be configurable).

To configure the levels in the TOC, I have previously used something like 
```javascript
toc = require('markdown-it-table-of-contents')

var md = new MarkdownIt({
  ...
}).use(toc, {
    "includeLevel": [1, 2, 3]
});

```

Thanks you!

**Comment by jannis-baum** [comment]
Ah nice, good to know. I'll be back later and add a config option for that similar to how we have it for KaTeX (math).

**Comment by jannis-baum** [comment]
All done! You can configure the levels (and everything else) in your config file, see [`docs/customization`](https://github.com/jannis-baum/Vivify/blob/main/docs/customization.md) for more information :)

Note that this is on main now but not yet released. If you already want it, you can either build the repo yourself or download the artifact from the CI-build from [here](https://github.com/jannis-baum/Vivify/actions/runs/10132570223) for your system, unpack it, and `chmod +x` to make both files executable

**Comment by twidxuga** [comment]
I finally had time to test, and the TOC shows up, but included levels are not respected, I can only ever get 1 and 2 (the default for the node module). The contents of my ~/.vivify.json are:

```json
{
  "includeLevel": [1, 2, 3]
}
```

Thanks again!

PS: I tried to build from git on Arch, but vivify-server dies with segmentation fault in all instances. The artifact from CI worked, though. `ldd`  lists a lot more libraries linked to the binary compiled on my local than that from CI - happy to raise an issue for it if relevant.

**Comment by Tweekism** [comment]
Hey Ricardo,

Thanks for testing that, I'll also test here in a minute to see if I can replicate the TOC thing.

As for your build issue might be related to a known issue using the Arch packaged version of node. If you have time, and are willing, have a look at our [CONTRIBUTONG](https://github.com/jannis-baum/Vivify/blob/main/docs/CONTRIBUTING.md) page, there is a fix for that.

**Comment by Tweekism** [comment]
So I got 3rd level heading working here...

Just to confirm, your config file at location `~/.vivify.json` looks like this:-

```
{
    "tocOptions": {
      "includeLevel": [1, 2, 3]
    }
}
```

![image](https://github.com/user-attachments/assets/e4e59982-8deb-4326-a7e0-e8f5d8ba0d3a)

**Comment by jannis-baum** [comment]
Hey @Tweekism thanks for looking into this already!

@twidxuga I also just tested the `"tocOptions"` again and it works for me as it does for @Tweekism.

**Comment by twidxuga** [comment]
Thanks, @jannis-baum and @Tweekism. I got it working, and it was indeed my fault: I was missing the `tocOptions` portion of the config. It was late yesterday, and I just copied the example config snippet from the docs. I realize now that the config snippets/examples in the docs do not have the higher level tags because they are mentioned in the bullet points.

> As for your build issue might be related to a known issue using the Arch packaged version of node. If you have time, and are willing, have a look at our [CONTRIBUTING](https://github.com/jannis-baum/Vivify/blob/main/docs/CONTRIBUTING.md#setting-up-your-build-environment) page, there is a fix for that.

Not a lot of time, but I'm motivated enough that I would like to make it work from source on Arch, and make an occasional issue/pull requests, thanks for the pointer. 

Thanks again for all the great work, really excited about Vivify!

**Comment by Tweekism** [comment]
I thought that might be the case. @jannis-baum  do you think it is worth including a little sample config or something to make that more clear?

**Comment by jannis-baum** [comment]
> Not a lot of time, but I'm motivated enough that I would like to make it work from source on Arch, and make an occasional issue/pull requests, thanks for the pointer.
> 
> Thanks again for all the great work, really excited about Vivify!

This is great to hear!

> I thought that might be the case. @jannis-baum do you think it is worth including a little sample config or something to make that more clear?

Maybe we just add the top level key to the two examples where we have actual snippets? I.e. in this case we write `"tocOptions": { ... }` where `...` is what we have right now. What do you think?

**Comment by Tweekism** [comment]
Yeah that should work.

**Comment by jannis-baum** [comment]
Done! #145
