### ISSUE TITLE
Linux bin depends on alias open=xdg-open

### ISSUE THREAD

**Issue by tuurep** [jannis-baum/vivify#14]
Hello, great project

I can't run the executable `viv` before changing the last line from `open $VIV_ADDR/viewer$FILE` to `xdg-open $VIV_ADDR/viewer$FILE`

Simple thing that might go unnoticed so thought I'd give a warning :)

**Comment by jannis-baum** [comment]
Hi, thanks for reporting! Can you try the `viv` executable in #15 to check if the fix works?

**Comment by tuurep** [comment]
Yeah, that worked. Thank you!

**Comment by jannis-baum** [comment]
Thank you!

---

Fixed in [v0.0.2](https://github.com/jannis-baum/vivify/releases/tag/v0.0.2)
