### ISSUE TITLE
Terminal exit fails when spawning vivify-server

### ISSUE THREAD

**Issue by palomino79** [jannis-baum/Vivify#169]
### Description

When running the `viv` shell script that starts a new server process in the background and then monitors the process with `monitor_server`, the terminal fails to close properly if the user attempts to exit the terminal while the script is still running. The `monitor_server` function, which continuously checks the server's status, remains attached to the terminal session, preventing the terminal from closing.

### To Reproduce

1. Do not have a running vivify-server instance.
2. Open a markdown file for preview with the command `viv some_file.md`
3. Attempt to exit the terminal, such as by issuing the `exit` command to the terminal.

### Context

Expected Behavior:

The terminal should close normally after starting the script, with all background processes continuing to run independently.

Actual Behavior:

The terminal fails to close and remains open until the monitor_server function or the server process completes. This prevents the terminal from exiting, requiring manual intervention to close the terminal.

> My operating system is:

Linux (flavor of Linux shouldn't matter for this problem).

> Running `viv --version` outputs:

```
vivify-server v0.5.0
```

> I installed Vivify in the following way (e.g. name of the package manager, self-compiled or development mode):

Self-compiled.

> This is what happens when I kill any running instance of Vivify with `killall vivify-server` and then run `vivify-server` at the absolute installation path (e.g. at `command -v vivify-server`) instead of `viv` and try to reproduce the problem:

The issue is purely in the `viv` executable script and how it monitors the server process.

**Comment by jannis-baum** [comment]
Interesting! Thanks for reporting this. I never realized that `monitor_server` doesn't exit because this doesn't prevent my shell or terminal from exiting for some reason like it does for you.

Anyways, should be fixed in #171, could you check that? Thanks!

**Comment by palomino79** [comment]
@jannis-baum Oh, man, you just beat me to it. I had a different idea of just disowning the function, but I'll see if your commit fixes the issue. Thanks. I'll close out the PR I just made.

**Comment by jannis-baum** [comment]
I released [0.5.1](https://github.com/jannis-baum/Vivify/releases/tag/v0.5.1) with the fix. Thanks again for your help!
