### ISSUE TITLE
Homebrew installation missing libraries

### ISSUE THREAD

**Issue by stephencroberts** [jannis-baum/Vivify#178]
[//]: # (Hello and thank you for taking the time to submit a bug report!       )

[//]: # (To make sure we can resolve this as quickly as possible, please       )
[//]: # (carefully fill out the information requested on this template.        )

[//]: # (Hint: Lines that look like these are Markdown comments and won't be   )
[//]: # (      visible on the issue after you submit it so you don't need to   )
[//]: # (      delete them.                                                    )

### Description

[//]: # (A clear and concise description of what the bug is and what you       )
[//]: # (expected to happen instead. Feel free to include additional material  )
[//]: # (such as screenshots if they contribute to the explanation.            )

I was really glad to see a homebrew option now as I had previously just downloaded the latest binaries for macOS, but this morning
I installed vivify with `brew install jannis-baum/tap/vivify` and `vivify-server` was crashing due to missing libraries. I had to install the following with `brew`:

- `libuv`
- `brotli`
- `c-ares`
- `icu4c`

The errors looked like this:

```txt
dyld[53474]: Library not loaded: /opt/homebrew/opt/icu4c/lib/libicui18n.74.dylib
  Referenced from: <ABEA7B93-1036-3221-BC61-120016BED223> /opt/homebrew/Cellar/vivify/0.5.1/bin/vivify-server
  Reason: tried: '/opt/homebrew/opt/icu4c/lib/libicui18n.74.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/icu4c/lib/libicui18n.74.dylib' (no such file), '/opt/homebrew/opt/icu4c/lib/libicui18n.74.dylib' (no such file)
```

### To Reproduce

[//]: # (A list of steps we can follow to consistently reproduce the bug       )
Reproducing is dependent on the environment, so best way would probably be with a clean macOS install, but simply:

- Install with homebrew
- Run `vivify-server`

### Context

[//]: # (Please fill out the following list                                    )

> My operating system is:

macOS 14.6.1

> Running `viv --version` outputs:

```txt
vivify-server v0.5.1
```

> I installed Vivify in the following way (e.g. name of the package manager, self-compiled or development mode):

Homebrew

> This is what happens when I kill any running instance of Vivify with `killall vivify-server` and then run `vivify-server` at the absolute installation path (e.g. at `command -v vivify-server`) instead of `viv` and try to reproduce the problem:

> In the following I specify if I use any custom configuration, and if so provide it in its entirety including any additional files referenced there (e.g. CSS or JavaScript):

**Comment by jannis-baum** [comment]
Hello! Great to finally see a fellow macOS user haha. Thanks a lot for already investigating so much!!

I checked and I have all the dependencies you listed installed already, probably from other packages, that's why I didn't realize they were dependencies. I just added them to the Homebrew Formula, so I'll close this. In case something is still not working feel free to reopen. Thanks!

**Comment by stephencroberts** [comment]
@jannis-baum Oh nice, good to hear you're on macOS! Thanks for responding so quickly. Great work, been loving this tool.
