### ISSUE TITLE
Add support for KaTeX configuration file

### ISSUE THREAD

**Issue by anzic0** [jannis-baum/vivify#23]
Optional file `~/.vivify/katex_config.json` in which [available KaTeX options](https://katex.org/docs/options.html) may be provided. In particular, it would be nice to be able to define custom macros.

I actually implemented this already, but need an issue to link to the pull request :)

**Comment by jannis-baum** [comment]
Nice! Looking forward to check out your PR!

One thought on the config file: I'm planning on introducing other config options (see #16). IMO we don't need separate config files but one should be enough, e.g. `~/.vivify.json` where we can have this as well as the stuff from #16. What do you think?

**Comment by jannis-baum** [comment]
But actually, the directory `~/.vivify/` makes sense because we could place custom CSS there as well. So maybe just `~/.vivify/config.json`?

**Comment by anzic0** [comment]
Yes, that sounds good!

**Comment by jannis-baum** [comment]
Thanks for the feature! I merged it, implemented #16 & #7 because it was fitting & released [our work](https://github.com/jannis-baum/vivify/releases/tag/v0.0.3)😊
