### ISSUE TITLE
Can't run `viv` / `:Vivify` on a directory (-buffer)

### ISSUE THREAD

**Issue by tuurep** [jannis-baum/vivify#27]
Hi I just noticed how Viv can be used as a handy file browser and loved how you've implemented that (apart from colors but I'll delve into that later :smile: ).

However it struck me as odd that you can't simply `viv <dir>` and the only way to get a directory listing in the browser was for me to first open a (regular) file and then navigate to parent with the hidden button (top left). 

It's not clear to me if this is a Linux vs MacOS issue. But either way I identified the problem and have a fix ready:

In the file `viv` you see if argument is a regular file:

```
if ! [ -f "$1" ]; then
    echo "$1 not found"
    exit 1
fi
```

You can add a directory check too:

`if ! [ -f "$1" ] && ! [ -d "$1" ]; then ...`

For me that fixes both `viv <dir>` on bash and `:Vivify` in a (n)vim directory buffer.

**Comment by jannis-baum** [comment]
Nice! Thanks! I think I added that file check before I came up with the directory browser haha.

---

> apart from colors but I'll delve into that later

Not sure if that already covers your wishes but you can [specify your own CSS file](https://github.com/jannis-baum/vivify#config) to change all the colors☺️

**Comment by tuurep** [comment]
Ah I see now. Thanks for the merges :)

Yea sorry, to be less vague about my color comment: I'd like to separate directories from regular files either by a different color or a trailing slash.

**Comment by jannis-baum** [comment]
> I'd like to separate directories from regular files either by a different color or a trailing slash.

I like this! feel free to open an issue and/or PR☺️ The trailing slash I'd definitely do. If we do the colors as well, maybe let's consider using some color/CSS class that is already defined by the syntax highlighting. That way it will work for people who use a premade syntax highlighting CSS.

**Comment by tuurep** [comment]
Great! I can definitely look into this later.

**Comment by tuurep** [comment]
Kinda related: bug trying to view the root directory `/`

Can't do it with parent directory button or `viv /`, but adding an extra slash on the end of the address field works just fine.

Probably an easy fix, I'll look at it soon.
