### ISSUE TITLE
Be less strict about markdown file extension

### ISSUE THREAD

**Issue by tuurep** [jannis-baum/vivify#29]
Noticed that Vivify doesn't consider a file with extension `.markdown` as a markdown file. I always thought `.md` and `.markdown` were the "normal" extensions for a markdown file. Turns out it's not well specified and there are more than these two.

I think I found out how to allow more than `.md` extension: in `src/parser/parser.ts` line 37  add another `... && fileEnding !== 'markdown'` and now I can work with files that have extension `.markdown`.

I propose to add an array of common markdown extensions and then something like `if fileEnding not in <thatArray> then ... Y'know`

I think we should go by what Vim (and NeoVim) set as filetype markdown by file-extension,

in `$VIMRUNTIME/filetype.vim` you can see that it's these:

```
.markdown
.mdown
.mkd
.mkdn
.mdwn
.md
```

nvim's `filetype.lua` uses the exact same ones.

**Comment by jannis-baum** [comment]
Closed in #30
