### ISSUE TITLE
CI not running on external PRs

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/vivify#31]
The CI doesn't run on fork branches so PRs end up not showing CI fails such as the linter complaining. Once we merge them it does fail on main though.

Example: On #30 the CI didn't run and then it failed on `main` after merging.

**Comment by jannis-baum** [comment]
@tuurep Do you maybe have an idea how to manage this?

**Comment by tuurep** [comment]
Oh. I'm unfamiliar with how these work, I see you fixed my `let` -> `const` mistake which I was most concerned about :smile:

**Comment by jannis-baum** [comment]
No worries haha. I'll look into how to make the CI run, I'm sure there should be a way

**Comment by jannis-baum** [comment]
I think I fixed it in #32, let's see if the CI runs on your next PR ^^
