### ISSUE TITLE
Various config.json issues

### ISSUE THREAD

**Issue by tuurep** [jannis-baum/vivify#33]
### Unlisted dependency on `jq`

Hi, the primary reason I filed this under "bug" is that I noticed to use the `config.json` file in the first place requires package `jq` to be installed on the user's system but this is not listed as a dependency for the project anywhere. I didn't have this installed and that was hard to pinpoint :smile: 

So for example, this package is a Vivify dependency for me: https://archlinux.org/packages/extra/x86_64/jq/

Maybe the readme should have a Dependencies -section, and do you know if there could be more?

### `"pageTitle"` doesn't seem to work with `basename` or `join`

If my goal is to set the pagetitle as `basename(path)`, what should I set on the key? I figured it should be this:

```
{
    "pageTitle": "basename(path)"
}
```

However each time I try this, using `viv` gives an "Unable to connect" firefox page.

What has worked as a `"pageTitle"` key:

* `"'foo'"` will show <title> as `foo`
* `"console.log('foo')"` will show <title> as `undefined` (correct, I think :smile: )
* `"path"` will show the full path, which is a good sign
  * Also: `"console.log(path)"` correctly shows `undefined`

Same issue (Unable to connect) applies for trying to use the `join` func, as an example:

* `"join('foo', path)"`

This is what the Firefox page looks like:

![image](https://github.com/jannis-baum/vivify/assets/15036238/a854a117-77a4-4ad6-b90a-4f0e968dea80)

**Comment by jannis-baum** [comment]
Thanks! I'll try and look into it in the next days :)

**Comment by tuurep** [comment]
Thanks, also I wanted to rule out the `"pageTitle"` problem being specific to only Firefox, and Vivaldi gives a very similar connection error page:

![image](https://github.com/jannis-baum/vivify/assets/15036238/e7474b6f-f9a1-4e89-b6d0-72c33fbe2fbe)

**Comment by tuurep** [comment]
I had an idea that since `basename` and `join` come from the module `path`, and we use the same name `path` as a variable name, that could mess it up. However, testing with a different variable name didn't help.

**Comment by jannis-baum** [comment]
I think #33 should cover everything; I would be happy about a review & testing! :)
