### ISSUE TITLE
Slightly indented first line of a `pre` code block

### ISSUE THREAD

**Issue by tuurep** [jannis-baum/vivify#38]
![image](https://github.com/jannis-baum/vivify/assets/15036238/789d979d-48b1-43fb-8963-48e4bf73f0e9)

Looking into this now!

Facts:
* Happens in every single `pre` block
* Not a space character `" "` but an alignment issue

**Comment by jannis-baum** [comment]
Nice! After this and the light mode are done we can [release `0.1.0`](https://github.com/jannis-baum/vivify/milestone/1). Or was there something else you wanted to include before?

**Comment by tuurep** [comment]
Yeah that's good!

I'm still interested in the `ä` in filenames issue, but that can be later (also I can't tell now if that's complicated or not),

and making the `AUR` package, but that can be a separate thing.

**Comment by jannis-baum** [comment]
> I'm still interested in the ä in filenames issue, but that can be later (also I can't tell now if that's complicated or not)

I'll say this really carefully and with a huge grain of salt but I think that should be pretty straight forward🙈 Maybe I'll find time tomorrow or early next week to try fixing it. If I don't make it before you finish the other two open issues then that can be 0.1.1 ^^

> and making the AUR package, but that can be a separate thing.

Oki once you want to start working on it, open an issue & then we can talk there. I have no idea how that works but in case we need any additional CI/CD related stuff for it I can help!

**Comment by tuurep** [comment]
> I'll say this really carefully and with a huge grain of salt but I think that should be pretty straight forward🙈 Maybe I'll find time tomorrow or early next week to try fixing it. If I don't make it before you finish the other two open issues then that can be 0.1.1 ^^

Sounds great!

> Oki once you want to start working on it, open an issue & then we can talk there. I have no idea how that works but in case we need any additional CI/CD related stuff for it I can help!

Yeah, I can totally take responsibility of the whole thing since to make sure the package works you'd have to run Arch Linux :D but 2 things: 

1. If you want to be co-maintainer of the package just ask
2. I can let you review the `PKGBUILD`s and there might be like a `yarn` / `tsc` build step or something like that which I'm a little unfamiliar with, and you can check if it looks correct. I can open an issue here for discussion later

### On the indent issue

Think I'm onto something!

https://github.com/jannis-baum/vivify/blob/68afc9b45880ba43d8f739e875ce13fa7c3bc7f9/src/parser/highlight.ts#L15

There if I remove the `<code>` tags, there's no indent issue although now the block has a bit of a left side padding like this:

![image](https://github.com/jannis-baum/vivify/assets/15036238/73c55b4c-4f64-4255-b4a5-51d5ccd62136)

That doesn't break syntax hl either:

![image](https://github.com/jannis-baum/vivify/assets/15036238/c6c4717d-5433-4c06-b5ab-3693664cbc13)

But should we try to still have it without the leftside padding? that probably looked better.

**Comment by tuurep** [comment]
Yeah by the way, if we were to look at Github for a guide, it opts for the big paddings, example:

![image](https://github.com/jannis-baum/vivify/assets/15036238/07ed4e4f-3f9b-4a55-a6b4-0d55e87fa088)

Do you have an aesthetic opinion? :D

**Comment by jannis-baum** [comment]
Ah, that makes sense! I think just in terms of the HTML semantics it's good to have `<pre><code>...</code></pre>`, so let's fix it in the CSS by `unset`ting the padding of `code`s in `pre`s like we do with the background color.

> Do you have an aesthetic opinion? :D

No strong opinion ^^ but I'd say styling it the way people know it from GitHub is always a good default option.
