### ISSUE TITLE
Render Jupyter Notebooks

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/vivify#55]
- follow https://github.com/jsvine/notebookjs for reference of reading through the `ipynb` file, also see [nbformat docs](https://nbformat.readthedocs.io/en/latest/format_description.html)
- use existing markdown parsing pipeline as much as possible, e.g.
  - code blocks with syntax highlighting
  - images actually also already work with Base64 in Vivify [like this](https://stackoverflow.com/a/50817623)
  - monospaced printed output is also just another code block with `plain` & [parsed ansi](https://www.npmjs.com/package/ansi_up)
  - markdown is markdown

**Comment by jannis-baum** [comment]
There is `nbconvert`, this is a bit slow though. Faster would be to have a Python server running that gives us the HTMLs, this way we could save some time on the initialization

```python
import nbformat
from nbconvert import HTMLExporter

notebook = nbformat.read('notebook_path', as_version=4)
html_exporter = HTMLExporter(template_name='classic')
(body, resources) = html_exporter.from_notebook_node(notebook)

print(body)
```

**Comment by jannis-baum** [comment]
Using Python here is not good; maybe we can reimplement https://github.com/jsvine/notebookjs with pluggable markdown parser & highlighting; then we can plug in Vivify's existing parser & highlighting

**Comment by jannis-baum** [comment]
@tuurep do you use Notebooks/are you interested in this feature as well?

**Comment by jannis-baum** [comment]
Sounds good! I was also avoiding them for the longest time haha but recently they have been adding up and I find myself in the browser running Jupyter Lab way too much.

My ultimate goal with this is to have Vivify render Notebooks very quickly and in its style and then make another Vim extension that uses [jupytext](https://github.com/mwouts/jupytext) to open and edit the `.ipynb` files and run a kernel in the background that we use to execute cells from Vim and then live-update the `.ipynb` to be displayed by Vivify🤩 Getting excited haha, then we will essentially have the same "edit in Vim, view in the browser" paradigm for Notebooks as for Markdown

**Comment by tuurep** [comment]
Actually, really cool :smile:
