### ISSUE TITLE
Github Flavored Markdown extended syntax support

### ISSUE THREAD

**Issue by tuurep** [jannis-baum/vivify#57]
Github Flavored Markdown syntax extensions:

- [x] Tables (style added in #58)
- [x] Task list
- [x] Strikethrough
- [x] Autolinks (added in #58)
- [ ] Footnotes (#59)

**Comment by jannis-baum** [comment]
Nice, thank you so much, this is great!

> Is it true that fixing the Extended Syntax that doesn't work depends mostly on the library markdown-it and what it supports?

Yes! Supporting any part of the extended syntax will come down to finding a good and well-maintained plugin for `markdown-it` and integrating it into Vivify.

> I'll definitely fix the style issues as soon as possible (tables, horizontal rule)

Thank you!!

> I would at least like Footnotes to be supported in Vivify.

I agree.

All the other things you mentioned that GitHub doesn't support I would argue we don't need either? Or at least I don't haha[^1]. But if your goal is for Vivify to support all extended syntax then I'll definitely support that :)

[^1]: Aside from footnotes the only thing here that I tend to use sometimes but very rarely are definition lists. When I use those they also need to be rendered on GitHub though so I usually opt for HTML.

**Comment by tuurep** [comment]
Hmmm... let's see, let's at least do these:

1. Tables style
2. Horizontal rule style
3. Footnotes

In case it would be simple and easy, of course would be nice to support all, but basically I agree. Interesting that you've used 'definition lists', I've never known about it and the markdown syntax for it would be really comfortable, but yeah since it doesn't render in github a lot of the usefulness is gone there.

What do you think about Automatic URL Linking though? That's something I'd likely use myself, but it's not a big deal to wrap links in `[]()` instead

**Comment by jannis-baum** [comment]
> What do you think about Automatic URL Linking though? That's something I'd likely use myself, but it's not a big deal to wrap urls in []() instead.

Yes this sounds good! Especially since GitHub does it as well. It's very easy to do natively with `markdown-it`, I'll add it to your PR :)

**Comment by jannis-baum** [comment]
Oh by the way, take a look at [this](https://www.npmjs.com/package/markdown-it#syntax-extensions); for lots of the main extended features like footnotes they recommend a plugin at `markdown-it` already. So let's use the recommendation where it exists

**Comment by tuurep** [comment]
> > What do you think about Automatic URL Linking though? That's something I'd likely use myself, but it's not a big deal to wrap urls in  instead.
> 
> Yes this sounds good! Especially since GitHub does it as well. It's very easy to do natively with `markdown-it`, I'll add it to your PR :)

Great, thank you!

> Oh by the way, take a look at [this](https://www.npmjs.com/package/markdown-it#syntax-extensions); for lots of the main extended features like footnotes they recommend a plugin at `markdown-it` already. So let's use the recommendation where it exists

Nice,

I see now btw that my list isn't really an accurate measure for markdown syntax completeness because there's all kinds of possible extended syntax

Maybe indeed it would be most practical to match all the syntax that Github does?

I'm trying to find a complete list of Github Flavored Markdown syntax support

Came across this: https://github.github.com/gfm/

But it's in a bit... overwhelming detail :smile:

**Comment by jannis-baum** [comment]
Yes I agree, aiming to cover what GitHub covers is good. Anything on top of that is not my personal priority but I don't mind having it if as long as it's not super rare & specific.

If you want we could rename this issue to "Full coverage of GitHub Markdown" or something and scratch the to-do's that GitHub doesn't have either? :)

> We could refer to this: https://github.github.com/gfm/
>
> But it's in a bit... overwhelming detail 😄 I'm trying to see if there's anything here that could be added

I found this: https://docs.github.com/en/get-started/writing-on-github but it's quite lengthy as well. I'd also be fine with trusting some random cheat-sheet like [this one](https://github.com/im-luka/markdown-cheatsheet#table-of-contents) for now haha

**Comment by tuurep** [comment]
Yeah, thanks for the links

I'll update this issue probably by tomorrow

**Comment by tuurep** [comment]
Hey, do you know what determines the top/bottom margin for headers?

![image](https://github.com/jannis-baum/vivify/assets/15036238/d99e3d35-479e-460b-84b1-f6fc4093e89b)

The yellow part in this

For `h1` it's `21.44px`, for `h2` `19.92px`

Reason why I'm asking is I think it might look best if I set the same top-margin for the footnotes section, assuming it's some relative value?

**Comment by jannis-baum** [comment]
Nice, thank you! The footnotes look great; copying GitHub's style sounds good as well.

> For h1 it's 21.44px, for h2 19.92px
>
> Reason why I'm asking is I think it might look best if I set the same top-margin for the footnotes section, assuming it's some relative value?
>
> Or maybe it could just be set to roughly 20px, I might be obsessing a bit but I feel like it needs juuust a little bit of top margin 😄

Hm I think it's just the browser's default CSS since we don't set any margin manually. Weird thing is though that I also have exactly 21.44px on Safari, i.e. the same you get on Chrome? Or was that screenshot also from Safari? Anyways, maybe Safari and Chrome just agree on that haha.

The actual value for `h1` is `0.67em` in my default Safari style by the way.

> But when I directly mimic Github's footnote section, setting a border-top on section.footnotes instead and setting .footnote { display: none; } (the hr element) I avoid all of those problems. That would be a fine solution IMO, what do you think?

Yes, totally fine!☺️

**Comment by tuurep** [comment]
> The actual value for h1 is 0.67em in my default Safari style by the way.

Ahh.. that helps, but can you tell me the `h2` `em` value too? I feel like exactly that could work well as footnotes margin-top.

**Comment by jannis-baum** [comment]
> Ahh.. that helps, but can you tell me the h2 em value too? I feel like exactly that could work well as footnotes margin-top.

Sorry, just now saw this!

```css
h2 {
    display: block;
    font-size: 1.5em;
    margin-block-start: 0.83em;
    margin-block-end: 0.83em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    font-weight: bold;
}
```

The margin is `0.83em` at a font size of `1.5em` so if I understand CSS units correctly the value you can use to get the same margin is `0.83em / 1.5em ≈ 0.55rem`.

> Oh yeah, nope, I'm using firefox in fact 😄

Nice good it's not Chrome lol
