### ISSUE TITLE
Figure out AUR packaging with Node SEA

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/vivify#71]
Based on discussion in #68

**Comment by tuurep** [comment]
What I'm planning to do next:

1. Set up `vivify-bin` in AUR that gets the current precompiled release
2. When we release, bump version number on that and see that it still works
3. Mark `vivify` (AUR) as Out-of-date with a comment about the [segfault issue](https://github.com/jannis-baum/vivify/pull/68#issuecomment-2220710742) in Node SEA

**Comment by tuurep** [comment]
Btw I'm noticing in some AUR PKGBUILDs that instead of `zip` or `unzip`, they typically use `bsdtar`

In case that could be used in `make linux`, noting this here!

**Comment by tuurep** [comment]
Ok, vivify-bin for version 0.1.6 works:

https://aur.archlinux.org/packages/vivify-bin

**Comment by jannis-baum** [comment]
> Btw I'm noticing in some AUR PKGBUILDs that instead of `zip` or `unzip`, they typically use `bsdtar` to work with `.zip` files
> 
> In case that could be used in `make linux`, noting this here!

Ah nice, and `bsdtar` is a program that is available on Arch by default? I swapped it out in #77, seems like it works :)

**Comment by jannis-baum** [comment]
> Ok, vivify-bin for version 0.1.6 works:
> 
> https://aur.archlinux.org/packages/vivify-bin

Great! So I assume that should mean that newer versions will also work?

**Comment by jannis-baum** [comment]
Alright! I was thinking to wait to merge all the currently open PRs (except for maybe the one about the `tar` thing) and then release v0.2.0 :)

---

Going to close this now then, we can keep talking about the `tar` thing on that PR

**Comment by tuurep** [comment]
All AUR packaging is working!

But gives me a thought about `make install`:

If I want to use `make install` in my PKGBUILD, I'd do like this:

```
./configure "${pkdir}/usr/bin"
make install
```

But currently that doesn't work if the install dir doesn't already exist

This does, of course:

```
mkdir -p "${pkdir}/usr/bin"
./configure "${pkdir}/usr/bin"
make install
```

(don't worry about what "${pkdir}" is, that's an AUR thing and unimportant)

So should `make install` actually be the one who does a `mkdir -p` first? What do you think?
