### ISSUE TITLE
Support full extended syntax

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/Vivify#87]
The only things missing are super/subscripts, "highlight" and custom heading ids: https://www.markdownguide.org/extended-syntax/

- [x] add markdown-it extensions for these
- [x] simplify the README and just say we support full extended syntax
- [x] add features to `markdown-extended` testing file

**Comment by tuurep** [comment]
I find this plugin for Custom Heading IDs but it can also add any attributes inside the curly brackets:

https://mdit-plugins.github.io/attrs.html

**Comment by Tweekism** [comment]
Right, so the reason I came looking for iamcco in the first place was to get these things working...

![Screenshot from 2024-07-14 01-51-37](https://github.com/user-attachments/assets/dad57727-9c5d-4ac1-925d-43b6d6af9d64)

I have a young lady working in my office and she likes things to be pretty.

This is how it looks on GitHub:

![Screenshot from 2024-07-14 01-52-44](https://github.com/user-attachments/assets/75e5e418-5b75-4d61-984f-b685d319db12)

Soooo.... add it to the list? 😅

**Comment by tuurep** [comment]
Interesting and looks great to me..

More information about those:

https://github.com/orgs/community/discussions/16925

Possible markdown-it plugin:

https://github.com/antfu/markdown-it-github-alerts

**Comment by jannis-baum** [comment]
Indeed interesting! I agree that it would be a cool addition.

> More information about those:
> 
> https://github.com/orgs/community/discussions/16925
> 
> Possible markdown-it plugin:
> 
> https://github.com/antfu/markdown-it-github-alerts
> 
> I think it goes more into the "additional" markdown but I would definitely be down to adding this

Nice, looks good! And yes, definitely in the "additional" section ^^ Considering this I will open a new issue for it since this issue focusses on only the official extended syntax

**Comment by jannis-baum** [comment]
Just to mention it again on this issue as well: Due to the changes made in #72 and #90 I would suggest either branching off from #90 or waiting until both PRs are merged to work on this. Should whoever wants to do it decide on branching off from it before it's merged, be aware that changes may still happen below where you branched off :)

**Comment by jannis-baum** [comment]
Additional research:

The attribute plugin works with our current anchor plugin: https://www.npmjs.com/package/markdown-it-anchor#manually-setting-the-id-attribute

Subscript: https://mdit-plugins.github.io/sub.html

Superscript: https://mdit-plugins.github.io/sup.html

Highlight/mark: https://mdit-plugins.github.io/mark.html#usage

---

In addition to these new features, it might make sense to consider changing some of the plugins we have for the more official versions from that site.
