### ISSUE TITLE
GitHub alert block quotes

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/Vivify#89]
- [x] add markdown-it plugin for rendering
- [ ] figure out colors

---

OP @Tweekism in https://github.com/jannis-baum/vivify/issues/87#issuecomment-2226968861

> Right, so the reason I came looking for iamcco in the first place was to get these things working...
> 
> ![Screenshot from 2024-07-14 01-51-37](https://github.com/user-attachments/assets/dad57727-9c5d-4ac1-925d-43b6d6af9d64)
> 
> I have a young lady working in my office and she likes things to be pretty.
> 
> This is how it looks on GitHub:
> 
> ![Screenshot from 2024-07-14 01-52-44](https://github.com/user-attachments/assets/75e5e418-5b75-4d61-984f-b685d319db12)
> 
> Soooo.... add it to the list? 😅
            
Research from @tuurep 

> More information about those:
> 
> https://github.com/orgs/community/discussions/16925
> 
> Possible markdown-it plugin:
> 
> https://github.com/antfu/markdown-it-github-alerts
> 
> I think it goes more into the "additional" markdown but I would definitely be down to adding this

**Comment by Tweekism** [comment]
Can I start looking into this? or are you already on it @tuurep

**Comment by jannis-baum** [comment]
Just as a quick disclaimer before anyone starts working on this:

In #72 we update all dependencies and in #78 I change Vivify from CommonJS to ESM which changes a few things around how importing modules works. So if you want to start working on this now, either be prepared to rebase things and solve the merge conflicts or branch off from after those changes were made, but then be aware that force pushes may still happen under your branch-off point

**Comment by tuurep** [comment]
This will probably be really simple, only thing I'm concerned about is dark theme colors :D

For light theme we can copy what Github uses:

alert type | left-side-border and title font color
:---------:|:------------------------------------:
Note       | `#0969da`
Tip        | `#1a7f37`
Important  | `#8250df`
Warning    | `#bf8700`
Caution    | `#cf222e`

The way Github names these color variables also reveals to me that they attach some meaning to these colors and reuse them in their UI:

* `#0969da` = `--fgColor-accent`
* `#1a7f37` = `--fgColor-success`
* `#8250df` = `--fgColor-done`
* `#bf8700` = `--fgColor-attention`
* `#cf222e` = `--fgColor-danger`

@jannis-baum does the dark theme have some existing colors that could fit? If not, I can cook up some suggestions.

**Comment by jannis-baum** [comment]
> This will probably be really simple, only thing I'm concerned about is dark theme colors :D
> 
> 
> 
> For light theme we can copy what Github uses:
> 
> 
> 
> alert type | left-side-border and title font color
> 
> :---------:|:------------------------------------:
> 
> Note       | `#0969da`
> 
> Tip        | `#1a7f37`
> 
> Important  | `#8250df`
> 
> Warning    | `#bf8700`
> 
> Caution    | `#cf222e`
> 
> 
> 
> The way Github names these color variables also reveals to me that they attach some meaning to these colors and reuse them in their UI:
> 
> 
> 
> * `#0969da` = `--fgColor-accent`
> 
> * `#1a7f37` = `--fgColor-success`
> 
> * `#8250df` = `--fgColor-done`
> 
> * `#bf8700` = `--fgColor-attention`
> 
> * `#cf222e` = `--fgColor-danger`
> 
> 
> 
> @jannis-baum does the dark theme have some existing colors that could fit? If not, I can cook up some suggestions.
> 
> 
> 
> **Edit:**
> 
> 
> 
> We could see how the ANSI colors look on it:
> 
> 
> 
> https://github.com/jannis-baum/dotfiles/blob/60e769172e2c2740999c3e7892a7530c75bd6a26/.lib/nosync/color-schemes/jellyfish.yaml#L57
> 
> 
> 
> blue-green-magenta-yellow-red

Yes, that sounds good! And actually, now that you mention ANSI, we should also use those colors for Notebooks. There we also have to render ANSI and the current default colors are very ugly

**Comment by tuurep** [comment]
Ok, but there's a chance a separation of the Alert colors and ANSI colors would be best, for example if we look at someone's take on an Alacritty Github Light theme:

![image](https://github.com/user-attachments/assets/03c2d125-4145-4511-b35a-bf6a3cacbcbc)

They're way different from the ones used in the alerts

**Comment by tuurep** [comment]
Wow turns out you're half correct, some are actually the same values

But something is strange about the yellow, I tried comparing like this:

![image](https://github.com/user-attachments/assets/86b66c7d-3c7f-49ea-b607-1e079b45a6f3)

Left: Github Alert color
Right: ANSI (non-bright) from the alacritty theme [here](https://github.com/projekt0n/github-theme-contrib/blob/main/themes/alacritty/github_light.yml)

In the screenshot I posted before it looked to me like the magenta was substantially darker so I thought that would be the case with all of them, since the Alert border is quite a large solid surface compared to code foreground (in an IPython error)

So yes turns out the ANSI colors and Github Alert colors are if not the same, very similar. We can get somewhere with this info :D

**Comment by tuurep** [comment]
So maybe lets try using ANSI for the Alerts as is, then see if something emerges like

* "this is unreadable, increase contrast"

adjust as needed?

**Comment by tuurep** [comment]
Wait what am I looking at :smile:

https://github.com/alacritty/alacritty-theme/blob/master/themes/github_light.toml

This is very different, lets see

**Comment by tuurep** [comment]
![image](https://github.com/user-attachments/assets/45400e4c-6c55-4f5b-89c2-b8253aa85e17)

Yeah I mean, this is what I *thought* I saw in the original screenshot, with the magenta being very dark

**Comment by tuurep** [comment]
Sorry I got confused by some outdated file there.

I still would favor distinguishing the (error) syntax highlighting and the alert colors

I'm obsessed with stuff like this so I can help you out, is that ok? :smile:

**Comment by jannis-baum** [comment]
> I still would favor distinguishing the (error) syntax highlighting and the alert colors
> 
> I'm obsessed with stuff like this so I can help you out, is that ok? 😄

Haha yes, of course! If it's important to you let's separate them for sure :)

**Comment by tuurep** [comment]
I investigated more and turns out this:

![image](https://github.com/user-attachments/assets/22b37894-af8b-4f6e-adf8-3aa0131c5ab6)

(source: https://github.com/projekt0n/github-theme-contrib)

is more up to date than this:

![image](https://github.com/user-attachments/assets/e6cfcf5b-812c-4aa1-84ec-80d3aee35755)

(source: https://github.com/alacritty/alacritty-theme)

So actually I'm leaning towards this suggestion again:

> So maybe lets try using [ANSI](https://github.com/jannis-baum/dotfiles/blob/60e769172e2c2740999c3e7892a7530c75bd6a26/.lib/nosync/color-schemes/jellyfish.yaml#L57) for the Alerts as is on the dark theme, then see if something emerges like
>
> * "this is unreadable, increase contrast"
>
> adjust as needed?

So plan of action:

1. Add the plugin
2. Add "known" colors (light theme)
3. Add ANSI colors (dark theme)
    * if some look bad, adjust a bit
4. ???
5. Think about IPython error syntax highlighting (in a separate issue preferably)

**Comment by jannis-baum** [comment]
Sounds like a good plan to me! :) I'll open the IPython-related issue, would you work on that one as well?

I can do #87 next then if you're working on these :)

**Comment by tuurep** [comment]
> I'll open the IPython-related issue, would you work on that one as well?

Yeah but could you describe your biggest gripes in:

> There we also have to render ANSI and the current default colors are very ugly

I've only taken a brief glance and wasn't *overly* horrible on Light Theme, but does it use the same colors for both Light and Dark?

**Comment by jannis-baum** [comment]
> > I'll open the IPython-related issue, would you work on that one as well?
> 
> Yeah but could you describe your biggest gripes in:
> 
> > There we also have to render ANSI and the current default colors are very ugly
> 
> I've only taken a brief glance and wasn't _overly_ horrible on Light Theme, but does it use the same colors for both Light and Dark?

I replied to this on the other issue #101
