### ISSUE TITLE
 Viv hanging on "Launching server..."

### ISSUE THREAD

**Issue by Tweekism** [jannis-baum/vivify#92]
Hey guys, 

Anyone seen this? viv hanging on "Launching server..." on the latest commit. Reverting to 09e4264 (Merge pull request #70) launches normally.

### To Reproduce

1. Built using latest commit on main 26421fac2a190eab6422868ce1871b62bb40ed0b
2. launch viv

### Screenshots

![image](https://github.com/user-attachments/assets/9269333e-d467-4194-b742-539531197259)

### Additional context

This is my work PC, a different PC to what I've been using over the weekend, so maybe I missed something? Running Fedora 40, same as home.

**Comment by jannis-baum** [comment]
Hello!

This version works for Tuure and me so let's see.

- What build is this, did you build yourself or did you download from the CI?
- If you built yourself, did you run `yarn` before building? Lots of packages were updated so this is necessary.
- If you did run `yarn` or use the CI build: What output do you get by just running `vivify-server` manually?
- And finally, if you built yourself, could you try the CI build or the other way around?

**Comment by Tweekism** [comment]
Ok, I don't know what to tell ya. I was able to replicate this issue several times this morning bouncing between 26421fac2a190eab6422868ce1871b62bb40ed0b - current main and 09e4264f2f5e0be82bcad166eaee90dfaa7beb07 - Merge #70, but now I can't. 

My current hypothesis is maybe there was some left over files from when I tried to build it from the system packaged node before downloading latest via nvm. I can try with a VM if you like but otherwise we can close this.

**Comment by jannis-baum** [comment]
Oki no worries! It was probably the `yarn` thing to be honest. If you check out the right old commit, run `yarn` there, and then go back and build, you can probably make it happen again.

The `viv` executable from the version on main will start the server and then wait until it's "healthy" to terminate. If the server crashes it won't terminate. This could happen because you had some module installed at a wrong version where it still compiles but crashes at runtime.

The new PR on ESM and config updates will change how the `viv` executable works. I think it's almost ready to merge, feel free to try it out as well :) 

Anyways, will close this one now then

**Comment by Tweekism** [comment]
Hey mate,

I know we closed this one, but I hit the same issue when I got home. So I triple checked `yarn` was up to date. Manually deleted all the complied binaries just to be sure. Then ran `make` again and then `vivify-server`.

Output was:-
```sh
 $ viv .
Launching server ...
^C^
 $ vivify-server 
node:internal/util/embedding:41
    throw new ERR_UNKNOWN_BUILTIN_MODULE(path);
    ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:sea
    at new NodeError (node:internal/errors:399:5)
    at embedderRequire (node:internal/util/embedding:41:11)
    at 8586 (/home/jason/.local/bin/vivify-server:2:2108635)
    at __webpack_require__ (/home/jason/.local/bin/vivify-server:2:3314800)
    at 365 (/home/jason/.local/bin/vivify-server:2:2043696)
    at __webpack_require__ (/home/jason/.local/bin/vivify-server:2:3314800)
    at 1859 (/home/jason/.local/bin/vivify-server:2:2036560)
    at __webpack_require__ (/home/jason/.local/bin/vivify-server:2:3314800)
    at /home/jason/.local/bin/vivify-server:2:3315484
    at /home/jason/.local/bin/vivify-server:2:3315511 {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}

Node.js v20.0.0

# Ran this to check my node version to confirm i had it set to v20.0.0 for some reason
 $ node --version
v20.0.0
```

So I updated node to latest (v22.4.1) and that fixed it.

**Comment by jannis-baum** [comment]
Ah, yes, seems like that's a version of Node from before they introduced SEA. We should figure out what exactly is the minimal working version and document that. Maybe you could add that to your current PR that is related the to Node distribution?
